# Lab: Formatting the output
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
# Minimize the number of invocations of the print() function
print("    *", "   * *", " *     *", " *     *",  "***   ***", "  *   *", "  *   *", "  *****", sep ="\n")
# Make the arrow twice as big (but keep the proportions)
print("     * ", "    * * ", "   *   * ", "  *     * ",  " ***   *** ", "   *   * ", "   *   * ", "   ***** ", sep ="\n \n")
# Duplicate the arrow
print("    *     "*2)
print("   * *    "*2)
print("  *   *   "*2)
print(" *     *  "*2)
print("***   *** "*2)
print("  *   *   "*2)
print("  *   *   "*2)
print("  *****   "*2)